### ISSUE TITLE
Work with 5.0.0-beta.2 ... but Fail with 5.0.0-beta.3

### ISSUE THREAD

**Issue by dglaude** [hydronics2/nrf52840-LED-hat#1]
I tested your code on a "Circuit Playground Bluefruit" running Circuit Python version 5.0.0-beta.2 and it works fine with minimal change (I had to change board.RED_LED to board.D13 and I have to put my device name).

It scan, find the device and start the count down of seconds.

But when trying with Circuit Python version 5.0.0-beta.3 I get a failure on the first line after being connected, that is the line that say "my_service = ble_connection[MyService]"

Here is the output when it fail.

> Yes, found our preipherial, let's connect
> scan done
> Traceback (most recent call last):
>   File "main.py", line 139, in <module>
>   File "adafruit_ble/__init__.py", line 100, in __getitem__
>   File "adafruit_ble/__init__.py", line 65, in _discover_remote
> _bleio.ConnectionError: Connection has been disconnected and can no longer be used. Create a new connection.

Maybe BLE API has change, or a regression.
But there is a behaviour change between 5.0.0-beta.2 and 5.0.0-beta.3 that
I'll be on DISCORD to chat with the expert and try to get a fix for this.

Regards

**Comment by dglaude** [comment]
While I had two failure (out of two attempt) on beta.3 and two success (out of two) on beta.2
I now tested 10 to 20 times on both version, and it works 95%.

It does not seems to be version related, but something 
> that happens when the connection disconnects

I will search for way to trigger that problem and re-connect in case of disconnection.

**Comment by hydronics2** [comment]
yea I also had trouble sometimes connecting. While it seemed to always connect right away the first time... if I lost connection (say I wondered away from the hat and lost BLE connection) I wasn't able to reconnect without restarting the hat. It seemed related to the hat firmware but I didn't keep digging. Thanks for trying!
